### PR TITLE
Ext: Istio Virtual Services

### LINKED ISSUE #1731: Extensibility: Move ISTIO Virtual Services to an extension
**Description**

Move STIO Virtual Services from the Busola codebase to an extension.

**Acceptance Criteria**

- [ ] The application behaves and looks similar - small changes are accepted 
- [ ] Test are adjusted
- [ ] We try to reuse the existing widgets.If new widgets are needed, they need to be created and documented
- [ ] If edit fields are YAML only, we introduce form base editor

### PR DESCRIPTION
**Pull request by Lyczeq**
**Description**

Changes proposed in this pull request:

- [x] Virtual Services List view
- [x] Virtual Service Form
   - [x] HTTP
   - [x] Modified KeyValuePair widget to handle the data structure: map<string, [StringMatch](https://istio.io/latest/docs/reference/config/networking/virtual-service/#StringMatch)>. Added docs including modifications.
   - [x] TLS
   - [x] TCP
   - [x] Gateways & Hosts
   - [x] Placeholders
- [x] Virtual Services Details view
   - [x] Linking to Gateways in the Table
   - [x] ResourceGraph relations
   - [x] Collapsible sections for:
       - [x] TCP
       - [x] TLS
       - [x] HTTP
- [x] Translations

To improve User Experience when using a modified `KeyValuePair` widget, the [Notification](https://github.com/kyma-project/busola/issues/1774) widget will be used.

**Related issue(s)**
Resolves #1731

### CODE REVIEW

**Comment by wchrapka** [comment]
The component bugs when the same label is entered twice

image

**Comment by wchrapka** [comment]
I think these are present in the schema but the form doesn't display them:
```
spec[].http.name
spec[].http.directResponse
```

**Review by wchrapka — DISMISSED** [review]

**Review by grego952 — APPROVED** [review]

**Review by wchrapka — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Pull request merged**
