### PR TITLE
Fixed Graph tooltip and added a Legend

### LINKED ISSUE #1394: Add legend to the CPU, Memory etc. graphs
**Description**

We have 2 graphs, one next to each other, one has a legend, and the other one doesn't.
I believe it would look better if we would stick to one approach in both graphs.

Screen Shot 2022-06-08 at 14 48 38

**Reasons**

Consistency plus the User will be sure which color corresponds to which value.

**Attachments**

### LINKED ISSUE #1528: Values in the graph look inverted in the tooltip free vs used
**Description**

**Expected result**

**Actual result**

image

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by Lyczeq**
**Description**

Changes proposed in this pull request:

- Fixed a bug of incorrect tooltip
- Added a legend to the graph
- Improved and added translations
- Moved GraphLegend component to the shared directory

**Related issue(s)**
Resolves #1528
Resolves #1394

### CODE REVIEW

**Review by dariadomagala — CHANGES_REQUESTED** [review]
The legend doesn't work for the pods graphs
Screen Shot 2022-07-05 at 10 55 42

**Review by dariadomagala — APPROVED** [review]

**Review by klaudiagrz — DISMISSED** [review]

**Review by dariadomagala — DISMISSED** [review]

**Review by dariadomagala — APPROVED** [review]

**Pull request merged**
