### PR TITLE
Fix Missing property in Create form YAML

### LINKED ISSUE #1621: Missing property "roleRef" when creating a Role and ClusterRole Binding
**Description**

It seems we are missing some sensitive defaults when creating a Role and ClusterRole Binding

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

image

### PR DESCRIPTION
**Pull request by mrCherry97**
**Description**

Changes proposed in this pull request:

- After checking all YAML's in create added missing properties to every template
- ...
- ...

**Related issue(s)**
Closes #1621

### CODE REVIEW

**Comment by mrCherry97** [comment]
TO DO: 
investigate regex for hosts in API Rules Create
image

**Review by dariadomagala — DISMISSED** [review]

**Review by Wawrzyn321 — APPROVED** [review]

**Pull request merged**
