### PR TITLE
Create for BTP instances & bindings

### PR DESCRIPTION
**Pull request by Wawrzyn321**
**Description**

Changes proposed in this pull request:

- Add create modal for BTP SB & Instances
- Add `pluralize`
- Rename `CreateDeploymentForm`
- Add handling for `parametersFrom`

**Related issue(s)**

### CODE REVIEW

**Review by dariadomagala — CHANGES_REQUESTED** [review]
* When I created a Service Binding with `["kkkkkk"]` as an array of sources, I got this error:
```ServiceBindings.create.js:43 Error: admission webhook "mservicebinding.kb.io" denied the request: v1alpha1.ServiceBinding.Spec: v1alpha1.ServiceBindingSpec.ParametersFrom: []v1alpha1.ParametersFromSource: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|rsFrom":["kkkkkk"],"|..., bigger context ...|s","parameters":{"ddd":"dddd"},"parametersFrom":["kkkkkk"],"secretName":"ssss","serviceInstanceName"|...```
even though the form was valid. When I removed the quotes, and just put `[kkkkkk]`, the form was invalid, but the call was ok.

**Comment by dariadomagala** [comment]
> * When I created a Service Binding with `["kkkkkk"]` as an array of sources, I got this error:
>   `ServiceBindings.create.js:43 Error: admission webhook "mservicebinding.kb.io" denied the request: v1alpha1.ServiceBinding.Spec: v1alpha1.ServiceBindingSpec.ParametersFrom: []v1alpha1.ParametersFromSource: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|rsFrom":["kkkkkk"],"|..., bigger context ...|s","parameters":{"ddd":"dddd"},"parametersFrom":["kkkkkk"],"secretName":"ssss","serviceInstanceName"|...`
>   even though the form was valid. When I removed the quotes, and just put `[kkkkkk]`, the form was invalid, but the call was ok.

now it throws parsing error for both scenarios

**Review by dariadomagala — COMMENTED** [review]
Screen Shot 2021-08-31 at 15 24 31
fix the translations

**Review by dariadomagala — APPROVED** [review]

**Review by dariadomagala — DISMISSED** [review]

**Review by klaudiagrz — DISMISSED** [review]

**Review by klaudiagrz — APPROVED** [review]

**Review by Sawthis — APPROVED** [review]

**Pull request merged**
