### PR TITLE
remove destination rules from core-ui

### PR DESCRIPTION
**Pull request by mrCherry97**
**Description**

Changes proposed in this pull request:

- remove old codebase,
- adjust tests,
- fix DR config map (mostly jsonata changes),
- remove DR `mjs` files

**Related issue(s)**
part of #1964

### CODE REVIEW

**Review by IwonaLanger — APPROVED** [review]

**Review by Lyczeq — COMMENTED** [review]
In `core-ui/src/hooks/useMessageList.js` I found an usage of `DestinationRules` and some other Istio resources. This is kept in `RESOURCE_PATH` map that is used in `formatInvolvedObject` component(?). Since those resources aren't in busola anymore we should find different way on how to handle navigation in Events view. I would propose to use a hook/state that keeps the information about the Nodes and then filter whether the involvedObject is there and then navigate to that.

**Comment by Lyczeq** [comment]
> In `core-ui/src/hooks/useMessageList.js` I found an usage of `DestinationRules` and some other Istio resources. This is kept in `RESOURCE_PATH` map that is used in `formatInvolvedObject` component(?). Since those resources aren't in busola anymore we should find different way on how to handle navigation in Events view. I would propose to use a hook/state that keeps the information about the Nodes and then filter whether the involvedObject is there and then navigate to that.

We've decided to adjust that when removing Luigi.

**Pull request merged**
