### PR TITLE
Change configs from json to yaml

### LINKED ISSUE #1875: Use YAML format for all busola configurations
**Description**

As we are using YAML format for our extensions, we should use the same format for all our configurations. Identify and align the rest of the busola-related configs to use YAML ( example busola-config )

**Acceptance Criteria**

- [x] Existing json configuration out there should still work.
   Safe way to apply busola-config changes to STAGE and PROD:
     - [x] Dev updated
     - [x] Busola-deploy -> add `config.yaml`
     - [x] Check that DEV is making only one call for yaml 
     - [x] Bump stage https://github.tools.sap/kyma/busola-deploy/pull/178
     - [x] Bump prod https://github.tools.sap/kyma/busola-deploy/pull/180
     - [x] check prod
     - [x] Remove the workaround https://github.com/kyma-project/busola/pull/1962
     - [x] Busola-deploy -> remove `config.json` from module https://github.tools.sap/kyma/busola-deploy/pull/181
     - [x] Busola-deploy -> remove `config.json` https://github.tools.sap/kyma/busola-deploy/pull/182
     - [x] check dev
     - [x] Bump stage + remove config.json https://github.tools.sap/kyma/busola-deploy/pull/183
     - [x] check stage
     - [x] Bump prod + remove config.json https://github.tools.sap/kyma/busola-deploy/pull/188
     - [x] check prod
     - [ ] align docs (`features.md`)
- [x] configs (busola-config, config, version, etc.) https://github.com/kyma-project/busola/pull/1932
- [x] JSON extensions https://github.com/kyma-project/busola/pull/1944
- [x] JS extensions (need to write generator) https://github.com/kyma-project/busola/pull/1933

### PR DESCRIPTION
**Pull request by mrCherry97**
**Description**

Changes proposed in this pull request:

- change defaultConfig, config, version,
- change docker and makefile command.

**Related issue(s)**
part of #1875

### CODE REVIEW

**Comment by mrCherry97** [comment]
Cluster to test: https://json-to-yaml.kmain.hasselhoff.shoot.canary.k8s-hana.ondemand.com/

**Review by Lyczeq — APPROVED** [review]

**Pull request merged**
