### PR TITLE
Clean json packages

### LINKED ISSUE #1274: Clean up package.jsons
**Description**

When we've had multiple microfrontends, we've had a shared package.json with the packages that are used among more than just one microfrontend. Now, we only have two frontends, and not many packages are actually shared between them, yet they are still in the main package.json. Please move the packages that are used only in one of those frontends, to theirs "sub-package.jsons".

**Reasons**

It's easier to read, and easier to maintain. It might also decrease the time to bootstap the app, and size of specific applications since not so many packages will be in their node_modules.

**Attachments**

### PR DESCRIPTION
**Pull request by wchrapka**
**Description**

Moves some of the dependencies from master to core-ui/core package. 

**Related issue(s)**
Closes  #1274

### CODE REVIEW

**Review by Wawrzyn321 — APPROVED** [review]

**Review by Wawrzyn321 — APPROVED** [review]

**Comment by wchrapka** [comment]
<html>
<body>


/test pre-busola-integration-test-k3s-namespace
--



</body>
</html>

**Review by Wawrzyn321 — APPROVED** [review]

**Pull request merged**
