### PR TITLE
Visualize crds

### PR DESCRIPTION
**Pull request by qbalukom**

### CODE REVIEW

**Comment by mrCherry97** [comment]
spec and DNS just go for a walk 
image

**Comment by mrCherry97** [comment]
Some strings have [] is it neccesary?
image

**Review by mrCherry97 — COMMENTED** [review]
Some improvement idea, maybe for a separate task. Can we make all the links real references?
image

**Comment by qbalukom** [comment]
> Some strings have [] is it neccesary? image With objects is the same problem image

yes, because those are an array of strings and an array of objects

**Review by akucharska — DISMISSED** [review]

**Review by NHingerl — DISMISSED** [review]

**Review by NHingerl — APPROVED** [review]

**Pull request merged**
