### PR TITLE
Revert "Refactor Edit Config Map to allow code editors (#1468)"

### PR DESCRIPTION
**Pull request by dariadomagala**
This reverts commit 31786ca7058c51b6d19911e53284f68fc72e9b7e.

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by Wawrzyn321 — APPROVED** [review]

**Review by Wawrzyn321 — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Comment by dariadomagala** [comment]
Fixed #1521

**Pull request merged**
