### PR TITLE
remove services

### LINKED ISSUE #2326: Move Services to an extension
**Description**
Some basic things are already done regarding moving Services to an extension and can be found in `tests/integration/fixtures/examples/services/configuration.yaml`.

 - [ ] Replace the current implementation with extensibility
 - [ ] Deploy to stage and Test all the edge cases on stage
 - [ ] Deploy to production
 - [ ] Remove old codebase
 - [ ] Add Create form
 - [ ] Adjust Tests to use extensions

### PR DESCRIPTION
**Pull request by mrCherry97**
**Description**

Changes proposed in this pull request:

- remove services "old" implementation,
- adjust the test for reduced permissions.

**Related issue(s)**
Closes #2326

### CODE REVIEW

**Comment by halamix2** [comment]
pre-busola-presubmirast-scannerr

**Review by akucharska — DISMISSED** [review]

**Review by IwonaLanger — DISMISSED** [review]

**Review by akucharska — APPROVED** [review]

**Pull request merged**
