### PR TITLE
Fix name validation

### LINKED ISSUE #1687: Name of configmap does not accept .
**Description**

Seems that validation is not allowing . in the name

**Expected result**

The name should accept . in the name

**Actual result**

**Steps to reproduce**

**Troubleshooting**

image

### PR DESCRIPTION
**Pull request by Wawrzyn321**
**Description**

Changes proposed in this pull request:

- Adjust regex to allow '.'

**Related issue(s)**

Closes #1687

### CODE REVIEW

**Review by mrCherry97 — APPROVED** [review]

**Comment by mrCherry97** [comment]
In my opinion, we have to make validation with `.` as default and for resources that allow names without it custom validation for only `-` allowing, but as we discuss on a daily, we are just changing regex for now.

**Comment by Wawrzyn321** [comment]
This is how it was done before, but I rolled it back after a daily discussion.

**Review by mrCherry97 — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Review by wchrapka — APPROVED** [review]

**Pull request merged**
