### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by akucharska**
**Description**

Changes proposed in this pull request:

- Unify translations in components-form
- Add translations in components

**Related issue(s)**

### CODE REVIEW

**Comment by Lyczeq** [comment]
When pushing this PR on the environments, adjust below translations in kyma-dashbord:

Functions - runtime
DNS Providers - type
OAuth2Clients - tokenEndpointAuthMethod
Probably in DestinationRules

**Comment by akucharska** [comment]
Functions - runtime - _**no changes are needed here**_
DNS Providers - type - _**no changes are needed here**_
OAuth2Clients - tokenEndpointAuthMethod - _**no changes are needed here**_
DestinationRules -Traffic Policy -> Load Balancer and Locality LB Settings - **Adjusted**
API Rules - Methods - **Adjusted**

**Review by Lyczeq — APPROVED** [review]

**Pull request merged**
