### PR TITLE
Update ExternalLink.js

### PR DESCRIPTION
**Pull request by jcawley5**
to fix issue

https://github.com/kyma-project/busola/issues/2248

### CODE REVIEW

**Comment by mrCherry97** [comment]
Hi @jcawley5 
thanks for your PR. We need one more change from you regarding to contributing to busola. You need to change deployment image for your PR number: https://github.com/jcawley5/busola/blob/patch-1/resources/web/deployment.yaml#L19 -> image: eu.gcr.io/kyma-project/busola-web:PR-2294
Please change it, and your PR will be reviewed, and tests could be run.

**Comment by mrCherry97** [comment]
@jcawley5 please run `npm run lint-fix` command and push changes

**Review by Lyczeq — APPROVED** [review]

**Pull request merged**
