### PR TITLE
Old Service Catalog removal

### LINKED ISSUE #1595: Remove old Service Catalog
**Description**

Since old Service Catalog is no longer used we can remove it from Busola.

**Reasons**

No point keeping it here.

**Tasks**

- [x] Remove catalog-related views.
- [x] Remove sublists from other resource views (e.g. `ServiceBindings` on Function details)
- [x] Remove packages used by catalog
- [x] Cleanup configuration (config-overrides.js, jsconfig etc)
- [x] Adjust tests
- [x] Adjust docs (e.g. features one)

### PR DESCRIPTION
**Pull request by Lyczeq**
**Description**

Changes proposed in this pull request:

- Uninstalled needless packages: styled-components, styled-components-grid, react-jsonschema-form, ajv
- Adjusted config-overrides and jsconfig files
- Removed needless components and files related to the service-catalog
- Removed Service Bindings relation in the Functions
- Removed AddonsConfigurations and ClusterAddonsConfiguration files
- Removed ApplicationMappings related code
- Removed other libraries: cross-fetch, moment, dompurify and semvar

**Related issue(s)**
Closes #1595

### CODE REVIEW

**Review by Wawrzyn321 — DISMISSED** [review]
LsomewhatGTM

**Review by majakurcius — DISMISSED** [review]

**Review by Wawrzyn321 — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Pull request merged**
