### PR TITLE
Store configuration in sessionStorage in Docker

### PR DESCRIPTION
**Pull request by Wawrzyn321**
**Description**

Changes proposed in this pull request:

- Replace `defaultStorage` for Docker builds
- Propagate storage to other scripts

Testing:

- You can check out Docker image: `docker run -p 3001:3001 wawrzyn321/busola-local-347`

**Related issue(s)**

### CODE REVIEW

**Comment by Wawrzyn321** [comment]
bruh

**Comment by Wawrzyn321** [comment]
BRUH

**Review by dariadomagala — APPROVED** [review]

**Review by dariadomagala — APPROVED** [review]

**Pull request merged**
