### PR TITLE
More triggers

### PR DESCRIPTION
**Pull request by qbalukom**
add an "init" trigger on:
- opening the form
- choosing a preset
- resetting the form

### CODE REVIEW

**Review by mrCherry97 — CHANGES_REQUESTED** [review]
looks good, first choosing preset is working properly, but changing between presets is not updating spec

**Review by mrCherry97 — APPROVED** [review]

**Review by akucharska — DISMISSED** [review]
Setting port in API Rules does not work in this branch

**Review by mrCherry97 — APPROVED** [review]

**Pull request merged**
